// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkdq9WrzOUIy6Z8fvRRjP6ZKgGmzHsGik',
    appId: '1:508139661405:web:f5eceb7eb965ad7db585b4',
    messagingSenderId: '508139661405',
    projectId: 'apprunnertips',
    authDomain: 'apprunnertips.firebaseapp.com',
    storageBucket: 'apprunnertips.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkC88ovhtR_FHnuM2l7fRrLilTnZFZBCo',
    appId: '1:508139661405:android:3d22696078e2994eb585b4',
    messagingSenderId: '508139661405',
    projectId: 'apprunnertips',
    storageBucket: 'apprunnertips.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiW7gTN__pm7HhLIKgRpY5Gdn_rIAN6lE',
    appId: '1:508139661405:ios:e5485da093c832fdb585b4',
    messagingSenderId: '508139661405',
    projectId: 'apprunnertips',
    storageBucket: 'apprunnertips.firebasestorage.app',
    iosBundleId: 'com.example.runnerTips',
  );

}